# Generated by Django 3.2.7 on 2021-09-11 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproduct', '0002_subcategory_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='tax_rate',
            new_name='taxRate',
        ),
        migrations.RemoveField(
            model_name='product',
            name='total_price',
        ),
    ]
