# Generated by Django 3.2.7 on 2021-09-11 10:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproduct', '0003_auto_20210911_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='taxRate',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(1)]),
        ),
    ]
