# Generated by Django 3.2.7 on 2021-09-11 10:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myproduct', '0004_alter_product_taxrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('loc', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='product-images')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='mrp',
            field=models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='product',
            name='productimage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myproduct.productimage'),
        ),
    ]
