# Generated by Django 3.2.7 on 2021-09-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproduct', '0005_auto_20210911_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productimage',
        ),
        migrations.AddField(
            model_name='product',
            name='productImage',
            field=models.ImageField(default=None, upload_to='product-images'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
